@startuml
class ModerationResponse {
    + Score : double <<get>> <<set>>
    + Action : string <<get>> <<set>>
    + Reason : string? <<get>> <<set>>
}
ModerationResponse -- "MessageId" Guid
@enduml

