@startuml
class AdminController {
    + AdminController(dbContext:ApplicationDbContext)
    + <<async>> GetAuditLogs(limit:int, cancellationToken:CancellationToken) : Task<ActionResult>
    + <<async>> GetUsers(skip:int, take:int, cancellationToken:CancellationToken) : Task<ActionResult<IEnumerable<UserResponse>>>
}
ControllerBase -- AdminController
@enduml

