@startuml
class ModerationController {
    + ModerationController(moderationService:ModerationService)
    + <<async>> Score(request:ModerationRequest, cancellationToken:CancellationToken) : Task<ActionResult<ModerationResponse>>
}
ControllerBase -- ModerationController
@enduml

