@startuml
class User {
    + UserName : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + DisplayName : string <<get>> <<set>>
    + PasswordHash : string <<get>> <<set>>
    + Role : string <<get>> <<set>> = "User"
    + IsFrozen : bool <<get>> <<set>>
    + FailedLoginAttempts : int <<get>> <<set>>
}
class "ICollection`1"<T> {
}
User -- "Id" Guid
User -- "LockoutUntilUtc" DateTime
User o-> "CreatedAtUtc" DateTime
User o-> "Messages<Message>" "ICollection`1"
User o-> "Posts<Post>" "ICollection`1"
User o-> "PostComments<PostComment>" "ICollection`1"
User o-> "PostReactions<PostReaction>" "ICollection`1"
User o-> "SentFriendRequests<FriendRequest>" "ICollection`1"
User o-> "ReceivedFriendRequests<FriendRequest>" "ICollection`1"
User o-> "Notifications<CommunityNotification>" "ICollection`1"
User o-> "SentDirectMessages<DirectMessage>" "ICollection`1"
User o-> "ReceivedDirectMessages<DirectMessage>" "ICollection`1"
@enduml

