@startuml
!include ..\..\style.puml
title UserResponse

class UserResponse {
    + UserName : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + DisplayName : string <<get>> <<set>>
    + Role : string <<get>> <<set>>
    + IsFrozen : bool <<get>> <<set>>
    + {static} FromEntity(user:Models.User) : UserResponse
    + Id : Guid
}
@enduml
