@startuml
!include ..\..\style.puml
title UpdateFriendRequestStatusRequest

class UpdateFriendRequestStatusRequest {
    + Status : string <<get>> <<set>> = "Pending"
    + ActorUserId : Guid
}
@enduml
